name: matcher
channels:
  - defaults
dependencies:
  - ca-certificates=2023.12.12
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - python=3.8.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - blinker==1.7.0
      - click==8.1.7
      - colorama==0.4.6
      - flask==3.0.2
      - h5py==3.10.0
      - importlib-metadata==7.0.1
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - line-profiler==4.1.2
      - markupsafe==2.1.5
      - numpy==1.24.4
      - opencv-python==4.9.0.80
      - pillow==10.2.0
      - pip==24.0
      - tqdm==4.66.2
      - werkzeug==3.0.1
      - zipp==3.17.0
